import {useRef,useState} from 'react';
import entries from './crossword-entries.json';
import {buildGrid} from './crossword-model';
import './crossword.css';
const model=buildGrid(entries);
model.errors.forEach(error=>console.warn(`[Crossword] ${error}`));
const solution=Object.fromEntries(Object.entries(model.cells).map(([key,c])=>[key,c.letter]));
const labels={EN:['DISCOVER MY STACK!','PLAY','Check','Reveal word','Reveal all','Reset','Across','Down','Select a square, then type. Space or Tab switches direction.','All correct! Now let’s talk →','Check the marked squares.','No errors so far.','Your tools, at a glance'],PT:['DESCUBRA MINHA STACK!','JOGAR','Verificar','Revelar palavra','Revelar tudo','Reiniciar','Horizontais','Verticais','Selecione uma casa e digite. Espaço ou Tab alterna a direção.','Tudo certo! Vamos conversar →','Confira as casas marcadas.','Nenhum erro até agora.','Ferramentas à primeira vista'],ES:['¡DESCUBRE MI STACK!','JUGAR','Comprobar','Revelar palabra','Revelar todo','Reiniciar','Horizontales','Verticales','Selecciona una casilla y escribe. Espacio o Tab cambia la dirección.','¡Todo correcto! Hablemos →','Revisa las casillas marcadas.','Sin errores hasta ahora.','Herramientas a primera vista']};
export function Crossword({language='EN'}) {
 const l=labels[language],lang=language.toLowerCase(),input=useRef(null);
 const [values,setValues]=useState(solution),[playing,setPlaying]=useState(false),[cell,setCell]=useState(model.words[0].cells[0]),[wordId,setWordId]=useState(0),[wrong,setWrong]=useState([]),[notice,setNotice]=useState('');
 const word=model.words[wordId];const completed=Object.keys(solution).every(k=>values[k]===solution[k]);
 function focus(){input.current?.focus({preventScroll:true});}
 function select(k){const ids=model.cells[k].entries;const next=k===cell&&ids.length>1?ids.find(id=>id!==wordId):(ids.includes(wordId)?wordId:ids.find(id=>model.words[id].direction===word.direction)??ids[0]);setCell(k);setWordId(next);focus();}
 function toggle(){const ids=model.cells[cell].entries;if(ids.length>1)setWordId(ids.find(id=>id!==wordId));}
 function move(amount){const index=word.cells.indexOf(cell);setCell(word.cells[Math.max(0,Math.min(word.cells.length-1,index+amount))]);}
 function enter(char){if(!playing)return;setValues(v=>({...v,[cell]:char}));setWrong(w=>w.filter(k=>k!==cell));setNotice('');move(1);}
 function keyboard(e){if(e.key==='Escape'){e.preventDefault();input.current?.blur();document.getElementById('crossword-check')?.focus();return;}if(e.key==='Tab'||e.key===' '){e.preventDefault();toggle();return;}if(e.key.startsWith('Arrow')){e.preventDefault();const horizontal=['ArrowLeft','ArrowRight'].includes(e.key),direction=horizontal?'across':'down';const id=model.cells[cell].entries.find(id=>model.words[id].direction===direction);if(id!==undefined)setWordId(id);const [r,c]=cell.split(',').map(Number),sign=['ArrowLeft','ArrowUp'].includes(e.key)?-1:1;for(let i=1;i<16;i++){const k=`${r+(horizontal?0:sign*i)},${c+(horizontal?sign*i:0)}`;if(model.cells[k]){setCell(k);setWordId(model.cells[k].entries.find(id=>model.words[id].direction===direction)??model.cells[k].entries[0]);break;}}return;}if(e.key==='Backspace'){e.preventDefault();if(!playing)return;const index=word.cells.indexOf(cell);const target=values[cell]?cell:word.cells[Math.max(0,index-1)];setValues(v=>({...v,[target]:''}));setCell(target);setWrong(w=>w.filter(k=>k!==target));return;}if(/^[a-z0-9]$/i.test(e.key)){e.preventDefault();enter(e.key.toUpperCase());}}
 function play(){setValues({});setPlaying(true);setWrong([]);setNotice('');setWordId(0);setCell(model.words[0].cells[0]);focus();}
 function check(){const mistakes=Object.keys(values).filter(k=>values[k]&&values[k]!==solution[k]);setWrong(mistakes);setNotice(mistakes.length?l[10]:l[11]);}
 const activeLabel=`${word.number} ${word.direction==='across'?l[6]:l[7]}, ${word.answer.length} ${lang==='en'?'letters':lang==='pt'?'letras':'letras'}: ${word.clues[lang]}`;
 return <section className="crossword-card" id="skills" aria-labelledby="crossword-title"><h2 id="crossword-title">{l[0]}</h2><p className="crossword-help">{l[8]} <span>{language==='EN'?'Esc exits the grid.':language==='PT'?'Esc sai da grade.':'Esc sale de la cuadrícula.'}</span></p><div className="active-clue" aria-live="polite">{activeLabel}</div><div className="crossword-board" style={{'--columns':model.width}} role="group" aria-label={l[0]}><input ref={input} className="crossword-keyboard" aria-label={activeLabel} value="" autoComplete="off" autoCapitalize="characters" spellCheck={false} onKeyDown={keyboard} onChange={e=>{const character=e.target.value.toUpperCase().replace(/[^A-Z0-9]/g,'').slice(-1);if(character)enter(character);}} />{Array.from({length:model.height*model.width},(_,index)=>{const row=Math.floor(index/model.width),col=index%model.width,k=`${row},${col}`,square=model.cells[k];return square?<button key={k} type="button" tabIndex={k===cell?0:-1} onClick={()=>select(k)} onKeyDown={keyboard} aria-label={`${square.number?`${square.number}, `:''}${row+1}, ${col+1}: ${values[k]||'blank'}`} aria-pressed={cell===k} className={`crossword-cell ${word.cells.includes(k)?'in-word':''} ${k===cell?'selected':''} ${wrong.includes(k)?'incorrect':''}`}><small>{square.number}</small><span>{values[k]||''}</span></button>:<span key={k} className="crossword-block" aria-hidden="true"/>;})}</div><div className="crossword-controls"><button className="hand-note" onClick={play}>{l[1]}</button><button id="crossword-check" onClick={check}>{l[2]}</button><button onClick={()=>{setValues(v=>({...v,...Object.fromEntries(word.cells.map(k=>[k,solution[k]]))}));setWrong(w=>w.filter(k=>!word.cells.includes(k)));}}>{l[3]}</button><button onClick={()=>{setValues(solution);setWrong([]);setNotice('');}}>{l[4]}</button><button onClick={play}>{l[5]}</button></div><p className="crossword-status" aria-live="polite">{playing&&completed?<a href="#contact">{l[9]}</a>:notice}</p><div className="crossword-clues">{['across','down'].map((dir,index)=><section key={dir}><h3>{l[6+index]}</h3><ol>{model.words.filter(w=>w.direction===dir).sort((a,b)=>a.number-b.number).map(w=><li key={w.id} value={w.number}><button className={w.id===wordId?'active':''} onClick={()=>{setWordId(w.id);setCell(w.cells[0]);focus();}} aria-label={`${w.number} ${dir}, ${w.answer.length} letters: ${w.clues[lang]}`}>{w.clues[lang]} ({w.answer.length})</button></li>)}</ol></section>)}</div><div className="answer-key"><h3>{l[12]}</h3>{[...new Set(entries.map(e=>e.category))].map(category=><div key={category}><strong>{category}</strong><span>{entries.filter(e=>e.category===category).map(e=><a key={e.answer} href={e.projectLink}>{e.answer}</a>)}</span></div>)}</div></section>;
}
