export const stack = [
  {word:'PYTHON',category:'Languages',projects:['jobhunter']},
  {word:'PLAYWRIGHT',category:'Automation',projects:['jobhunter']},
  {word:'MONGODB',category:'Data',projects:['jobhunter']},
  {word:'REACT',category:'Web',projects:['portfolio']},
  {word:'FASTAPI',category:'Web',projects:['lumiere']},
  {word:'ESP32',category:'Hardware',projects:[]},
  {word:'JAVASCRIPT',category:'Languages',projects:['lumiere','portfolio']},
  {word:'CLAUDE',category:'AI',projects:['portfolio']},
  {word:'LINUX',category:'Operations',projects:[]},
  {word:'CODEX',category:'AI',projects:['portfolio']},
  {word:'APIS',category:'Integration',projects:['jobhunter','lumiere']},
  {word:'ETL',category:'Data',projects:['jobhunter']},
  {word:'MYSQL',category:'Data',projects:[]},
  {word:'GCP',category:'Cloud',projects:['jobhunter']},
];
